SET SESSION FOREIGN_KEY_CHECKS=0;


/* Create Tables */

CREATE TABLE REPORTS
(
	ID int NOT NULL,
	REPORTER_ID varchar(20) NOT NULL,
	REPORTED_ID varchar(20) NOT NULL,
	REPORT_CATEGORY varchar(20) NOT NULL,
	REPORT_CONTENT varchar(255) NOT NULL,
	REPORT_DATE date DEFAULT NOW(), SYSDATE() NOT NULL,
	REPORT_COUNT decimal,
	REVIEW_STATUS varchar(20) NOT NULL,
	ADMIN_ID int NOT NULL,
	ID_a int NOT NULL,
	ID_b int NOT NULL,
	PRIMARY KEY (ID)
);



