CREATE TABLE ADMINS
(
   ID int NOT NULL,
   ADMIN_ID varchar(255) NOT NULL,
   ADMIN_PASSWORD varchar(255) NOT NULL,
   ADMIN_NAME varchar(255) NOT NULL,
   ADMIN_EMAIL varchar(255) NOT NULL,
   ADMIN_PHONE char(13) NOT NULL,
   ADMIN_BIRTHDAY TIMESTAMP,
   ADMIN_GENDER char(1) NOT NULL,
   ADMIN_CREATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
   ADMIN_UPTIMESTAMP_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
   PRIMARY KEY (ID)
);